[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_staking = "AtnsmbdumGmkvn9j4fBy9pSk2XyKEv6WsqWHQXg2BUvH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# add these two macros to get the tests to pass properly
[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"